# Generated by Django 6.0 on 2026-05-13 20:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('organization_type', models.CharField(choices=[('university', 'Universidad'), ('business_school', 'Escuela de Negocios'), ('trading_academy', 'Academia de Trading'), ('corporate', 'Empresa Corporativa'), ('bootcamp', 'Bootcamp'), ('other', 'Otro')], max_length=20, verbose_name='tipo de organización')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('country', models.CharField(max_length=100, verbose_name='país')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/', verbose_name='logo')),
                ('primary_color', models.CharField(default='#3b82f6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Formato de color hexadecimal inválido')], verbose_name='color primario')),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Formato de color hexadecimal inválido')], verbose_name='color secundario')),
                ('custom_domain', models.CharField(blank=True, help_text='Ej: trading.universidad.edu', max_length=100, verbose_name='dominio personalizado')),
                ('max_students', models.IntegerField(default=100, verbose_name='máximo estudiantes')),
                ('max_instructors', models.IntegerField(default=10, verbose_name='máximo instructores')),
                ('subscription_plan', models.CharField(choices=[('basic', 'Básico - 50 estudiantes'), ('standard', 'Estándar - 200 estudiantes'), ('premium', 'Premium - 500 estudiantes'), ('enterprise', 'Empresarial - Ilimitado')], default='basic', max_length=20, verbose_name='plan de suscripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('subscription_start', models.DateTimeField(verbose_name='inicio de suscripción')),
                ('subscription_end', models.DateTimeField(verbose_name='fin de suscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='fin de prueba')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='configuraciones')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='título')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='departamento')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='ID empleado')),
                ('can_manage_students', models.BooleanField(default=True, verbose_name='gestionar estudiantes')),
                ('can_manage_instructors', models.BooleanField(default=True, verbose_name='gestionar instructores')),
                ('can_create_courses', models.BooleanField(default=True, verbose_name='crear cursos')),
                ('can_view_analytics', models.BooleanField(default=True, verbose_name='ver analytics')),
                ('can_manage_billing', models.BooleanField(default=False, verbose_name='gestionar facturación')),
                ('can_export_data', models.BooleanField(default=True, verbose_name='exportar datos')),
                ('can_manage_organization', models.BooleanField(default=False, verbose_name='gestionar organización')),
                ('notify_new_students', models.BooleanField(default=True, verbose_name='notificar nuevos estudiantes')),
                ('notify_course_completion', models.BooleanField(default=True, verbose_name='notificar completación de cursos')),
                ('notify_low_performance', models.BooleanField(default=True, verbose_name='notificar bajo rendimiento')),
                ('weekly_reports', models.BooleanField(default=True, verbose_name='reportes semanales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('is_primary_admin', models.BooleanField(default=False, verbose_name='administrador principal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador de Organización',
                'verbose_name_plural': 'Administradores de Organización',
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('invitation_type', models.CharField(choices=[('admin', 'Administrador'), ('instructor', 'Instructor'), ('student', 'Estudiante')], max_length=20, verbose_name='tipo de invitación')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('expires_at', models.DateTimeField(verbose_name='expira el')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceptado el')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='permisos')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Invitación de Organización',
                'verbose_name_plural': 'Invitaciones de Organización',
                'unique_together': {('organization', 'email', 'invitation_type')},
            },
        ),
    ]
