# Generated by Django 6.0 on 2025-12-08 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10, verbose_name='tipo de operación')),
                ('cantidad', models.DecimalField(decimal_places=10, help_text='Cantidad de criptomonedas', max_digits=20, verbose_name='cantidad')),
                ('precio_promedio', models.DecimalField(decimal_places=8, help_text='Precio en USD por unidad', max_digits=20, verbose_name='precio promedio')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Total en USD (cantidad * precio)', max_digits=20, verbose_name='monto total')),
                ('comision', models.DecimalField(decimal_places=8, default=0, help_text='Fee de la operación', max_digits=20, verbose_name='comisión')),
                ('fecha_operacion', models.DateTimeField(verbose_name='fecha de operación')),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada')], default='completada', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('criptoactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='backtesting.criptoactivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-fecha_operacion'],
            },
        ),
    ]
