# Generated by Django 6.0 on 2026-05-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='comision',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Fee calculado automáticamente: 0.1% exchange + 1.5% conversión PEN→USD (solo simulación educativa)', max_digits=20, verbose_name='comisión simulada'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, help_text='Total en USD (cantidad × precio)', max_digits=20, verbose_name='monto total'),
        ),
    ]
