# Generated by Django 6.0 on 2026-05-24 23:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileGuestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del dispositivo móvil', unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Nombre del dispositivo (ej: iPhone de Juan)', max_length=100)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Mobile')], default='android', max_length=20)),
                ('fcm_token', models.TextField(blank=True, help_text='Token de Firebase Cloud Messaging para push notifications')),
                ('enabled_alerts', models.BooleanField(default=True, help_text='Si el dispositivo quiere recibir alertas')),
                ('price_alerts', models.BooleanField(default=True, help_text='Alertas de cambios significativos de precio')),
                ('market_news', models.BooleanField(default=True, help_text='Noticias importantes del mercado')),
                ('system_announcements', models.BooleanField(default=True, help_text='Anuncios del sistema')),
                ('max_alerts_per_hour', models.PositiveIntegerField(default=5, help_text='Máximo número de alertas por hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id'], name='mobile_aler_device__5deb05_idx'), models.Index(fields=['enabled_alerts', 'last_active_at'], name='mobile_aler_enabled_4cbf9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MobileAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Si esta suscripción está activa')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_rule', models.ForeignKey(help_text='Regla de alerta del sistema a la que está suscrito', limit_choices_to={'is_system': True}, on_delete=django.db.models.deletion.CASCADE, to='alerts.alertrule')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='mobile_alerts.mobileguestdevice')),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='mobile_aler_device__aaba65_idx')],
                'unique_together': {('device', 'alert_rule')},
            },
        ),
        migrations.CreateModel(
            name='MobileNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('delivered', 'Entregada'), ('failed', 'Falló'), ('clicked', 'Clickeada')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='mobile_alerts.mobileguestdevice')),
                ('notification', models.ForeignKey(help_text='Notificación original del sistema de alertas', on_delete=django.db.models.deletion.CASCADE, to='alerts.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'delivery_status'], name='mobile_aler_device__943cdb_idx'), models.Index(fields=['sent_at'], name='mobile_aler_sent_at_912938_idx')],
            },
        ),
    ]
