# Generated by Django 4.2.7 on 2025-10-17 21:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criptoactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ej: BTC, ETH, ADA', max_length=20, unique=True, verbose_name='symbol')),
                ('name', models.CharField(help_text='Ej: Bitcoin, Ethereum', max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('market_cap_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='market cap rank')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Criptoactivo',
                'verbose_name_plural': 'Criptoactivos',
                'ordering': ['market_cap_rank', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tipo_estrategia', models.CharField(choices=[('scalping', 'Scalping'), ('day_trading', 'Day Trading'), ('swing_trading', 'Swing Trading'), ('position_trading', 'Position Trading'), ('arbitrage', 'Arbitraje'), ('grid_trading', 'Grid Trading'), ('dca', 'Dollar Cost Averaging'), ('custom', 'Personalizada')], max_length=20, verbose_name='strategy type')),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('paused', 'Pausada'), ('archived', 'Archivada')], default='draft', max_length=20, verbose_name='status')),
                ('max_risk_per_trade', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='max risk per trade (%)')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='max drawdown (%)')),
                ('timeframe', models.CharField(default='1h', help_text='Ej: 1m, 5m, 15m, 1h, 4h, 1d', max_length=10, verbose_name='timeframe')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('tipo_evento', models.CharField(choices=[('buy_signal', 'Señal de Compra'), ('sell_signal', 'Señal de Venta'), ('stop_loss', 'Stop Loss'), ('take_profit', 'Take Profit'), ('entry_condition', 'Condición de Entrada'), ('exit_condition', 'Condición de Salida')], max_length=20, verbose_name='event type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('condition_logic', models.TextField(help_text='Lógica de la condición en formato JSON o texto', verbose_name='condition logic')),
                ('priority', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['tipo_evento', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(help_text='Ej: RSI, MACD, SMA', max_length=20, unique=True, verbose_name='code')),
                ('tipo', models.CharField(choices=[('trend', 'Tendencia'), ('momentum', 'Momentum'), ('volatility', 'Volatilidad'), ('volume', 'Volumen'), ('custom', 'Personalizado')], max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, help_text='Esquema JSON de parámetros requeridos', verbose_name='parameters schema')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['tipo', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEstrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_detalle', models.CharField(choices=[('entry_rule', 'Regla de Entrada'), ('exit_rule', 'Regla de Salida'), ('risk_management', 'Gestión de Riesgo'), ('position_sizing', 'Tamaño de Posición'), ('filter', 'Filtro'), ('parameter', 'Parámetro')], max_length=20, verbose_name='detail type')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('configuration', models.JSONField(default=dict, help_text='Configuración específica en formato JSON', verbose_name='configuration')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='backtesting.estrategia')),
            ],
            options={
                'verbose_name': 'Detalle de Estrategia',
                'verbose_name_plural': 'Detalles de Estrategias',
                'ordering': ['estrategia', 'tipo_detalle', 'order'],
                'unique_together': {('estrategia', 'tipo_detalle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioEstrategiaCriptoactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('stopped', 'Detenida'), ('backtesting', 'En Backtesting')], default='active', max_length=20, verbose_name='status')),
                ('capital_asignado', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=15, verbose_name='assigned capital')),
                ('custom_risk_per_trade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='custom risk per trade (%)')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('criptoactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_estrategias', to='backtesting.criptoactivo')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_criptoactivos', to='backtesting.estrategia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias_criptoactivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Estrategia Criptoactivo',
                'verbose_name_plural': 'Usuario Estrategias Criptoactivos',
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'estrategia', 'criptoactivo')},
            },
        ),
        migrations.CreateModel(
            name='IndicadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, help_text='Parámetros específicos del indicador para este evento', verbose_name='parameters')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=8, help_text='Valor umbral para el indicador', max_digits=15, null=True, verbose_name='threshold value')),
                ('comparison_operator', models.CharField(choices=[('>', 'Mayor que'), ('<', 'Menor que'), ('>=', 'Mayor o igual que'), ('<=', 'Menor o igual que'), ('==', 'Igual a'), ('!=', 'Diferente de'), ('cross_above', 'Cruza por encima'), ('cross_below', 'Cruza por debajo')], default='>', help_text='Operador de comparación para evaluar el indicador', max_length=20, verbose_name='comparison operator')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='weight')),
                ('evaluation_order', models.PositiveIntegerField(default=1, verbose_name='evaluation order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='backtesting.evento')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='backtesting.indicador')),
            ],
            options={
                'verbose_name': 'Indicador Evento',
                'verbose_name_plural': 'Indicadores Eventos',
                'ordering': ['evento', 'evaluation_order'],
                'unique_together': {('indicador', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='EventoEstrategiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, help_text='Parámetros específicos del evento para este detalle', verbose_name='parameters')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='weight')),
                ('evaluation_order', models.PositiveIntegerField(default=1, verbose_name='evaluation order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('detalle_estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='backtesting.detalleestrategia')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategia_detalles', to='backtesting.evento')),
            ],
            options={
                'verbose_name': 'Evento Estrategia Detalle',
                'verbose_name_plural': 'Eventos Estrategias Detalles',
                'ordering': ['detalle_estrategia', 'evaluation_order'],
                'unique_together': {('evento', 'detalle_estrategia')},
            },
        ),
    ]
