# Generated by Django 6.0 on 2026-05-24 02:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest_type', models.CharField(choices=[('demo', 'Demo (parámetros fijos)'), ('custom', 'Personalizado')], max_length=10, verbose_name='tipo')),
                ('symbol', models.CharField(max_length=20, verbose_name='símbolo')),
                ('timeframe', models.CharField(max_length=10, verbose_name='timeframe')),
                ('fecha_inicio', models.CharField(max_length=20, verbose_name='fecha inicio del período')),
                ('fecha_fin', models.CharField(max_length=20, verbose_name='fecha fin del período')),
                ('capital_inicial', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='capital inicial')),
                ('capital_final', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='capital final')),
                ('ganancia_perdida', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='PnL')),
                ('rentabilidad_porcentaje', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='rentabilidad %')),
                ('operaciones_totales', models.PositiveIntegerField(default=0, verbose_name='operaciones totales')),
                ('operaciones_ganadas', models.PositiveIntegerField(default=0, verbose_name='operaciones ganadas')),
                ('operaciones_perdidas', models.PositiveIntegerField(default=0, verbose_name='operaciones perdidas')),
                ('tasa_acierto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='tasa de acierto %')),
                ('racha_perdidas', models.PositiveIntegerField(default=0, verbose_name='racha de pérdidas')),
                ('velas_negativas', models.PositiveIntegerField(default=0, verbose_name='velas negativas')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Sharpe ratio')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Max drawdown %')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='parámetros utilizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de backtest',
                'verbose_name_plural': 'Resultados de backtest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'created_at'], name='backtesting_usuario_c99a6f_idx')],
            },
        ),
    ]
