# Generated by Django 6.0 on 2026-05-24 02:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.CharField(max_length=240, verbose_name='descripción')),
                ('icon', models.CharField(help_text='emoji o caracter', max_length=8, verbose_name='icono')),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], default='common', max_length=12, verbose_name='rareza')),
                ('criteria', models.CharField(max_length=240, verbose_name='criterio en lenguaje humano')),
                ('is_system', models.BooleanField(default=False, verbose_name='badge del sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL = badge global del sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_badges', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['organization_id', 'rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('metric', models.CharField(choices=[('pnl', 'PnL acumulado'), ('win_rate', 'Win Rate'), ('trades', 'Operaciones'), ('backtests', 'Backtests realizados'), ('roi', 'ROI'), ('streak_days', 'Racha de días'), ('sharpe_ratio', 'Sharpe ratio'), ('custom', 'Personalizado')], max_length=20, verbose_name='métrica')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='valor objetivo')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='unidad')),
                ('reward_points', models.PositiveIntegerField(default=0, verbose_name='puntos de recompensa')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil'), ('epic', 'Épico')], default='medium', max_length=10, verbose_name='dificultad')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('archived', 'Archivado')], default='draft', max_length=12, verbose_name='estado')),
                ('is_global', models.BooleanField(default=True, verbose_name='asignar a toda la org')),
                ('start_date', models.DateTimeField(verbose_name='fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='organizations.organization')),
                ('reward_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_in_challenges', to='gamification.badge')),
            ],
            options={
                'verbose_name': 'Reto',
                'verbose_name_plural': 'Retos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='valor actual')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progreso %')),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completado'), ('failed', 'No completado')], default='in_progress', max_length=12, verbose_name='estado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completado en')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='última evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gamification.challenge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_assignments', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Asignación de reto',
                'verbose_name_plural': 'Asignaciones de retos',
                'ordering': ['-progress_percentage', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_awards', to='gamification.badge')),
                ('challenge', models.ForeignKey(blank=True, help_text='Reto que originó el otorgamiento, si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='gamification.challenge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_badges', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Badge de integrante',
                'verbose_name_plural': 'Badges de integrantes',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberGamificationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='puntos totales')),
                ('current_streak_days', models.PositiveIntegerField(default=0, verbose_name='racha actual (días)')),
                ('longest_streak_days', models.PositiveIntegerField(default=0, verbose_name='racha más larga')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='última actividad')),
                ('challenges_completed', models.PositiveIntegerField(default=0, verbose_name='retos completados')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profiles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profiles', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Perfil de gamificación',
                'verbose_name_plural': 'Perfiles de gamificación',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(verbose_name='puntos (+/-)')),
                ('source', models.CharField(choices=[('challenge_completion', 'Reto completado'), ('badge_award', 'Badge otorgado'), ('manual_adjustment', 'Ajuste manual')], max_length=24, verbose_name='origen')),
                ('reference_id', models.CharField(blank=True, max_length=40, verbose_name='referencia (uuid)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Transacción de puntos',
                'verbose_name_plural': 'Transacciones de puntos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['organization', 'status'], name='gamificatio_organiz_ebf17f_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', 'end_date'], name='gamificatio_status_aa1bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeassignment',
            index=models.Index(fields=['member', 'status'], name='gamificatio_member__887229_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeassignment',
            index=models.Index(fields=['challenge', 'status'], name='gamificatio_challen_9bb162_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeassignment',
            unique_together={('challenge', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='memberbadge',
            unique_together={('member', 'badge', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='membergamificationprofile',
            unique_together={('member', 'organization')},
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['member', 'organization'], name='gamificatio_member__5178eb_idx'),
        ),
    ]
