# Generated by Django 6.0 on 2026-05-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='metric',
            field=models.CharField(choices=[('trades', 'Operaciones realizadas'), ('backtests', 'Backtests realizados'), ('active_days', 'Días activos'), ('streak_days', 'Días consecutivos'), ('distinct_assets', 'Criptoactivos distintos operados'), ('win_rate', 'Win Rate (%)'), ('sharpe_ratio', 'Sharpe ratio'), ('pnl', 'PnL acumulado'), ('roi', 'ROI'), ('custom', 'Personalizado')], max_length=20, verbose_name='métrica'),
        ),
    ]
