# Generated by Django 6.0 on 2026-05-13 02:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('template_type', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('specialized', 'Especializado')], max_length=20, verbose_name='tipo de plantilla')),
                ('default_duration_weeks', models.IntegerField(default=12, verbose_name='duración por defecto (semanas)')),
                ('default_credits', models.IntegerField(default=3, verbose_name='créditos por defecto')),
                ('default_passing_grade', models.IntegerField(default=70, verbose_name='calificación mínima por defecto (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'Plantilla de Curso',
                'verbose_name_plural': 'Plantillas de Cursos',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('description', models.TextField(verbose_name='descripción')),
                ('semester', models.CharField(blank=True, max_length=50, verbose_name='semestre')),
                ('credits', models.IntegerField(default=3, verbose_name='créditos')),
                ('start_date', models.DateTimeField(verbose_name='fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha de fin')),
                ('enrollment_deadline', models.DateTimeField(verbose_name='fecha límite de inscripción')),
                ('allow_backtesting', models.BooleanField(default=True, verbose_name='permitir backtesting')),
                ('backtesting_symbols', models.JSONField(default=list, help_text='Lista de símbolos permitidos para backtesting', verbose_name='símbolos de backtesting')),
                ('max_backtesting_period', models.IntegerField(default=365, verbose_name='período máximo de backtesting (días)')),
                ('passing_grade', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='calificación mínima (%)')),
                ('max_quiz_attempts', models.IntegerField(default=3, verbose_name='máximo intentos de quiz')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='configuraciones')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseLessonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='orden')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoria')),
                ('custom_passing_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='puntuación mínima personalizada (%)')),
                ('max_attempts', models.IntegerField(blank=True, null=True, verbose_name='máximo intentos')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='disponible desde')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='disponible hasta')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='enterprise_courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_configs', to='lessons.lesson')),
                ('unlock_after_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='enterprise_courses.courselessonconfig')),
            ],
            options={
                'verbose_name': 'Configuración de Lección en Curso',
                'verbose_name_plural': 'Configuraciones de Lecciones en Cursos',
                'ordering': ['order'],
                'unique_together': {('course', 'lesson')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='enabled_lessons',
            field=models.ManyToManyField(related_name='enterprise_courses', through='enterprise_courses.CourseLessonConfig', to='lessons.lesson'),
        ),
        migrations.CreateModel(
            name='TemplateLessonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='orden')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoria')),
                ('week_number', models.IntegerField(default=1, verbose_name='semana')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_configs', to='lessons.lesson')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_lessons', to='enterprise_courses.coursetemplate')),
            ],
            options={
                'verbose_name': 'Configuración de Lección en Plantilla',
                'verbose_name_plural': 'Configuraciones de Lecciones en Plantillas',
                'ordering': ['order'],
                'unique_together': {('template', 'lesson')},
            },
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='lessons',
            field=models.ManyToManyField(related_name='templates', through='enterprise_courses.TemplateLessonConfig', to='lessons.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('organization', 'code')},
        ),
    ]
