# Generated by Django 6.0 on 2026-05-13 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('web_user', 'Usuario Web'), ('mobile_user', 'Usuario Móvil'), ('company', 'Empresa Web')], default='web_user', max_length=20, verbose_name='profile type'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='nombre de empresa')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='RUC / NIF / Tax ID')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='industria')),
                ('company_size', models.CharField(choices=[('1-10', 'Micro (1-10 empleados)'), ('11-50', 'Pequeña (11-50 empleados)'), ('51-200', 'Mediana (51-200 empleados)'), ('200+', 'Grande (200+ empleados)')], default='1-10', max_length=20, verbose_name='tamaño de empresa')),
                ('company_website', models.URLField(blank=True, verbose_name='sitio web corporativo')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='logo de empresa')),
                ('company_address', models.TextField(blank=True, verbose_name='dirección')),
                ('company_country', models.CharField(blank=True, max_length=100, verbose_name='país')),
                ('company_city', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('notify_reports', models.BooleanField(default=True, verbose_name='notificaciones de reportes')),
                ('notify_students', models.BooleanField(default=True, verbose_name='notificaciones de estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresa',
            },
        ),
    ]
