# Generated by Django 6.0 on 2026-05-13 02:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_courses', '__first__'),
        ('lessons', '0001_initial'),
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institutional_id', models.CharField(help_text='ID institucional del estudiante', max_length=50, verbose_name='ID estudiantil')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inscripción')),
                ('expected_graduation', models.DateTimeField(blank=True, null=True, verbose_name='graduación esperada')),
                ('status', models.CharField(choices=[('enrolled', 'Inscrito'), ('active', 'Activo'), ('completed', 'Completado'), ('dropped', 'Retirado'), ('suspended', 'Suspendido')], default='enrolled', max_length=20, verbose_name='estado')),
                ('overall_grade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='calificación general')),
                ('lessons_completed', models.IntegerField(default=0, verbose_name='lecciones completadas')),
                ('quizzes_passed', models.IntegerField(default=0, verbose_name='quizzes aprobados')),
                ('backtests_performed', models.IntegerField(default=0, verbose_name='backtests realizados')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='tiempo invertido (minutos)')),
                ('custom_settings', models.JSONField(blank=True, default=dict, verbose_name='configuraciones personalizadas')),
                ('instructor_notes', models.TextField(blank=True, help_text='Notas del instructor', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enterprise_courses.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción de Estudiante',
                'verbose_name_plural': 'Inscripciones de Estudiantes',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'organization', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('academic', 'Académica'), ('behavioral', 'Comportamental'), ('attendance', 'Asistencia'), ('performance', 'Rendimiento'), ('general', 'General')], default='general', max_length=20, verbose_name='tipo de nota')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('content', models.TextField(verbose_name='contenido')),
                ('is_private', models.BooleanField(default=False, verbose_name='privada')),
                ('is_important', models.BooleanField(default=False, verbose_name='importante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='student_management.studentenrollment')),
            ],
            options={
                'verbose_name': 'Nota de Estudiante',
                'verbose_name_plural': 'Notas de Estudiantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No Iniciada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('skipped', 'Omitida')], default='not_started', max_length=20, verbose_name='estado')),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progreso (%)')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='tiempo invertido (minutos)')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='puntuación')),
                ('max_score', models.FloatField(blank=True, null=True, verbose_name='puntuación máxima')),
                ('attempts', models.IntegerField(default=0, verbose_name='intentos')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completado el')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='último acceso')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='lessons.lesson')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='student_management.studentenrollment')),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progreso de Lecciones',
                'ordering': ['lesson__order'],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='enterprise_courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='organizations.organization')),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='student_management.studentenrollment')),
            ],
            options={
                'verbose_name': 'Grupo de Estudiantes',
                'verbose_name_plural': 'Grupos de Estudiantes',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
