# Generated by Django 5.2.4 on 2025-11-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Categoría de Lección',
                'verbose_name_plural': 'Categorías de Lecciones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20, verbose_name='Dificultad')),
                ('lesson_type', models.CharField(choices=[('theory', 'Teoría'), ('practical', 'Práctica'), ('quiz', 'Quiz'), ('simulation', 'Simulación')], max_length=20, verbose_name='Tipo de Lección')),
                ('duration_minutes', models.IntegerField(verbose_name='Duración (minutos)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL del Video')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessoncategory')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Quiz')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('passing_score', models.FloatField(default=70.0, verbose_name='Puntuación Mínima (%)')),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True, verbose_name='Límite de Tiempo (minutos)')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('true_false', 'Verdadero/Falso'), ('text', 'Texto Libre')], max_length=20, verbose_name='Tipo de Pregunta')),
                ('points', models.FloatField(default=1.0, verbose_name='Puntos')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.quiz')),
            ],
            options={
                'verbose_name': 'Pregunta de Quiz',
                'verbose_name_plural': 'Preguntas de Quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Respuesta')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Es Correcta')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.quizquestion')),
            ],
            options={
                'verbose_name': 'Respuesta de Quiz',
                'verbose_name_plural': 'Respuestas de Quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Puntuación Obtenida')),
                ('max_score', models.FloatField(verbose_name='Puntuación Máxima')),
                ('percentage', models.FloatField(verbose_name='Porcentaje')),
                ('passed', models.BooleanField(verbose_name='Aprobado')),
                ('time_taken_minutes', models.IntegerField(verbose_name='Tiempo Utilizado (minutos)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Quiz',
                'verbose_name_plural': 'Intentos de Quiz',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No Iniciada'), ('in_progress', 'En Progreso'), ('completed', 'Completada')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Progreso (%)')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='Tiempo invertido (minutos)')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Puntuación')),
                ('max_score', models.FloatField(blank=True, null=True, verbose_name='Puntuación Máxima')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progreso de Lecciones',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
